# Generated by Django 5.2.7 on 2025-11-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='slug_name',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
    ]
